# Generated by Django 5.2.4 on 2025-07-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('score', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
    ]
